Homework1
made-ml-in-prod-2021/azamatsab pull request #2
Opened 2021-05-09 20:07 UTC by azamatsab

2021-05-17 10:38 UTC, kindofman requested changes
Для форматирования кода в соответствии с PEP-8 рекомендую использовать black.

2021-05-17 10:38 UTC, kindofman commented on ml_project/src/report_generator.py
> +from src.utils import check_dir
Внутри проекта лучше использовать относительный импорт
```suggestion
from entities.config import ReportConfig
from utils import check_dir
```

2021-05-17 10:38 UTC, kindofman commented on ml_project/setup.py
> +import setuptools
Зачем 2 способа установки пакетов? Через setup.py и через requirements.txt.

2021-05-17 10:38 UTC, kindofman commented on ml_project/README.md
> +- Используется hydra  (https://hydra.cc/docs/intro/)
Для того, чтобы 13 пункт был зачтен, необходимо присвоить себе оценку в баллах.

2021-05-17 15:43 UTC, azamatsab commented on ml_project/setup.py
> +import setuptools
убрал установку пакетов из setup.py

2021-05-17 16:05 UTC, azamatsab commented on ml_project/src/report_generator.py
> +from src.utils import check_dir
Исправил. 

> Для форматирования кода в соответствии с PEP-8 рекомендую использовать black.

Запустил black, кроме замены ' на " ничего не изменилось. 
Насчет строк 10 и 11 из ml_project/src/report_generator.py: в первом случае импортится класс, во втором функция, вроде все по pep-8

2021-05-17 16:07 UTC, azamatsab commented on ml_project/README.md
> +- Используется hydra  (https://hydra.cc/docs/intro/)
Провел оценку

2021-05-23 10:21 UTC, kindofman commented on ml_project/src/report_generator.py
> +from src.utils import check_dir
Без этого исправления у меня проект не запустился.

2021-05-23 10:22 UTC, kindofman approved these changes
Отличная работа!

35 баллов

2021-05-23 11:08 UTC, merged