Homework3
made-ml-in-prod-2021/azamatsab pull request #4
Opened 2021-06-09 17:47 UTC by azamatsab

2021-06-16 17:36 UTC, Ulia-Demidova requested changes

2021-06-16 17:36 UTC, Ulia-Demidova commented on airflow_ml_dags/README.md
> +#### See the results of successful runs at screen folder
Ваши скриншоты не показывают того, что запуски прошли корректно.
Добавьте что то типа этого в описание к pr, тогда можно будет понять, работает ли что то:
<img width="1437" alt="Снимок экрана 2021-06-14 в 12 30 08" src="https://user-images.githubusercontent.com/43049817/122266229-445fec80-cee2-11eb-9d68-3ebe5cd949d8.png">

2021-06-17 05:32 UTC, azamatsab commented on airflow_ml_dags/README.md
> +#### See the results of successful runs at screen folder
Спасибо за ревью! Вы заметили что справа есть схема, где все даги загораются темно-зеленым? Это ведь и есть признак успешного запуска. Или этого недостаточно? В целом согласен что картинки нужно было делать во весь экран для большей репрезентативности, но пока боюсь пушить без запроса от teachers 

![retrain](https://user-images.githubusercontent.com/24545631/122336676-06ed7480-cf5f-11eb-9bef-dbd5e521599a.png)

2021-06-17 10:55 UTC, Ulia-Demidova commented on airflow_ml_dags/README.md
> +#### See the results of successful runs at screen folder
Да, извиняюсь, не увидела; когда открываешь картинки в гите нужно проскролить вправо, чтобы увидеть всю картинку. Тогда сегодня вечером посмотрю код

2021-06-18 09:32 UTC, Ulia-Demidova commented on airflow_ml_dags/README.md
> +#### See the results of successful runs at screen folder
Тут оказалось, что много ревью нельзя брать, а я уже сделал 2 ревью по этому заданию. Назначьте плиз другого

2021-06-21 06:10 UTC, Mikhail-M approved these changes
Если не ошибаюсь, то 

Баллы: 5+10+5+10+3 = 33

2021-06-21 09:04 UTC, merged